esphome:
  name: screek-human-sensor-l13
  comment: Screek Human Sensor L13
  friendly_name: Human Sensor L13
  name_add_mac_suffix: True
  platformio_options:
    board_build.flash_mode: dio
  project: 
    name: Screek.Human Sensor L13
    version: v1.0.0

logger:

preferences:
    flash_write_interval: 5s

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf

improv_serial:

debug:
  update_interval: 30s
api:

ota:
  - platform: esphome

safe_mode:
  disabled: true

wifi:

captive_portal:

web_server:
  port: 80
  
text_sensor:
  - platform: debug
    reset_reason:
      name: ESP Reset Reason
      icon: mdi:anchor
      disabled_by_default: True
  - platform: wifi_info
    ssid:
      name: ESP Connected SSID
      icon: mdi:wifi
      entity_category: diagnostic
      disabled_by_default: True
    ip_address:
      name: ESP IP Address
      icon: mdi:ip-network
      entity_category: diagnostic
      disabled_by_default: True
    mac_address:
      name: ESP MAC
      icon: mdi:wifi
      entity_category: diagnostic
      disabled_by_default: True
  - platform: ld2412
    version:
      name: LD2412S Firmware Version
      entity_category: diagnostic
    mac_address:
      name: LD2412S Mac
      entity_category: diagnostic


binary_sensor:
  - platform: status
    name: Online
    entity_category: diagnostic
  - platform: ld2412
    has_target:
      name: Presence
      id: presence_status
      on_press:
        then:
          - light.turn_on: presence_led
      on_release: 
        then:
          - light.turn_off: presence_led
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    dynamic_background_correction_status:
      name: LD2412S Dynamic Background Correction Status
      entity_category: diagnostic

sensor:
  - platform: internal_temperature
    name: ESP Temperature
    entity_category: diagnostic
  - platform: uptime
    name: ESP Uptime
    entity_category: diagnostic
    type:
      timestamp
  - platform: wifi_signal
    name: RSSI
    entity_category: diagnostic
  - platform: ld2412
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Moving Energy
    still_energy:
      name: Still Energy
  - platform: bh1750
    name: Illuminance
    address: 0x23
    update_interval: 1s
    
light:
  - platform: status_led
    id: sys_status
    pin: 
      number: GPIO13
      ignore_pin_validation_error: True
    restore_mode: ALWAYS_OFF
  - platform: status_led
    id: presence_led
    entity_category: config
    pin: 
      number: GPIO12
      ignore_pin_validation_error: True
    restore_mode: ALWAYS_OFF

time:
  - platform: sntp

esp32_improv:
  authorizer: none

switch:
  - platform: gpio
    id: bh1750_ground
    pin: GPIO2
    restore_mode: ALWAYS_OFF
  - platform: ld2412
    bluetooth: 
      name: LD2412S BLE Control
      entity_category: config
  - platform: template
    name: Presence Light
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      if:
        condition:
          binary_sensor.is_on: presence_status
        then:
          - light.turn_on: presence_led
    on_turn_off:
      - light.turn_off: presence_led

button:
  - platform: restart
    name: ESP Reboot
    entity_category: config
  - platform: factory_reset
    name: ESP Factory Reset
    entity_category: config
    disabled_by_default: True
  - platform: ld2412
    restart:
      name: LD2412S Reboot
      entity_category: config
    factory_reset:
      name: LD2412S Factory Reset
      entity_category: config
      disabled_by_default: True
    start_dynamic_background_correction:
      name: LD2412S Start Dynamic Background Correction
      entity_category: config

uart:
  tx_pin: 
    number: GPIO11
    mode:
      input: true
      pullup: true
  rx_pin: 
    number: GPIO7
    mode:
      input: true
      pullup: true
  baud_rate: 115200
  parity: NONE
  stop_bits: 1
  data_bits: 8

i2c:
  sda: 10
  scl: 3
  scan: True

ld2412:
